name: First Workflow
on: workflow_dispatch
jobs:
  DemoJob:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: |
          echo "Hello! Welcome to GHA.."
          echo "This is ${{github.actor}}"
      - name: Send Off
        run: |
          echo "Tata"
          echo "Bye bye!!!"
  
