name: First Workflow
on: workflow_dispatch
jobs:
  DemoJob:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: |
          echo "Hello! Welcome to GHA.."
          echo "This is ${{github.actor}}"
      - name: Clone the code
        run: |
          git clone https://github.com/ManojSaiK/github-actions-with-react.git
          cd github-actions-with-react
          npm ci
      - name: Send Off
        run: |
          echo "Tata"
          echo "Bye bye!!!"
  
